name: twitter_openapi_dart
version: 0.0.1
description: Twitter OpenAPI Dart
homepage: https://github.com/vrchatapi/vrchatapi-dart

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dio: '>=4.0.1 <5.0.0'
  json_annotation: '^4.4.0'

dev_dependencies:
  build_runner: any
  json_serializable: '^6.1.5'
  test: ^1.16.0
