name: twitter_openapi_dart
description: It is a Dart implementation of Twitter's internal API. It is available without special API tokens and also supports GraphQL endpoints.
version: 0.0.5
repository: https://github.com/fa0311/twitter_openapi_dart

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  intl: ">=0.17.0 <0.19.0"
  cookie_jar: ^4.0.1
  dio: "^5.0.0"
  dio_cookie_manager: ^3.0.0
  twitter_openapi_dart_generated: ^0.0.4
  collection: ">=1.15.0 <2.0.0"
  built_value: ">=8.4.0 <9.0.0"
  built_collection: ">=5.1.1 <6.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  built_value_generator: ">=8.4.0 <9.0.0"
  build_runner: any
